language: node_js
node_js:
- '4.3'

before_install:
  - npm install -g serverless

script:
  - serverless decrypt --stage dev --password $SLS_ENCRYPT_KEY 
  - serverless deploy --verbose

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  # - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
